# Etapa 1: Builder
FROM node:22-alpine AS builder

WORKDIR /usr/src/app

# Instala dependências
COPY package*.json ./
RUN npm ci

# Copia todo o restante do projeto
COPY . .

# Garante que pastas existam e tenham permissão
RUN mkdir -p /usr/src/app/assets \
    && mkdir -p /usr/src/app/public \
    && chown -R node:node /usr/src/app

# Build da aplicação
RUN npm run build

# Remove dependências de desenvolvimento
RUN npm prune --production


# Etapa 2: Produção
FROM node:22-alpine AS production

WORKDIR /usr/src/app
ENV NODE_ENV=production

# Configura timezone
RUN apk add --no-cache tzdata
ENV TZ=America/Sao_Paulo

# Copia artefatos do builder
COPY --from=builder /usr/src/app/dist ./dist
###COPY --from=builder /usr/src/app/assets ./assets
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./package.json

# Ajusta permissões para o usuário "node"
RUN chown -R node:node /usr/src/app

USER node

EXPOSE 8089

CMD ["node", "dist/server.js"]